version: "3.8"

services:
    frontend:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: development
        ports:
            - 4173:4173
