version: "3.8"

services:
    sampleproject:
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 4173:4173
