version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=db;Port=3306;Database = SailDB;User = root; Password = Lowisa;"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lowisa 
      MYSQL_DATABASE: SailDB 
      MYSQL_USER: root 
      MYSQL_PASSWORD: Lowisa 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge