name: CI

on:
  push:
  workflow_dispatch:
  
jobs:
  linting_checks:
    name: Linting Checks
    uses: ./.github/workflows/linting-checks.yml

  unit_tests:
    name: Unit Tests
    if: ${{ always() }}
    needs: linting_checks
    uses: ./.github/workflows/unit-tests.yml
    
  integration_tests:
    name: Integration Tests
    if: ${{ always() }}
    needs: unit_tests
    uses: ./.github/workflows/integration-tests.yml 