name: CI

on:
  workflow_dispatch:
  
jobs:

  linting_checks:
    name: Linting Checks
    uses: ./.github/workflows/linting-checks.yml

  unit_tests:
    name: Unit Tests
    if: ${{ always() }}
    needs: linting_checks
    uses: ./.github/workflows/unit-tests.yml

    
  integration_tests:
    name: Integration Tests
    if: ${{ always() }}
    needs: [unit_tests, linting_checks]
    uses: ./.github/workflows/integration-tests.yml 

  regression_tests:
    name: Regression Tests
    if: ${{ always() }}
    needs: [unit_tests, integration_tests]
    runs-on: ubuntu-latest