name: Development


on:
  workflow_run:
    workflows: [Manual CI Trigger]
    types: [completed]
  pull_request:
    types: [opened, reopened]
  push:
    branches: ['!main']


jobs:

#======================================================
# Linting
#======================================================

  flutter-linting:
    name: Flutter Lint Check
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend/flutter_client
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - name: Print
        run: |
          echo Flutter: No linting checks
        
  react-linting:
    name: REACT Lint Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo REACT: No Unit tests

  backend-linting:
    name: Backend Lint Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo Backend: No Unit tests

  lint-test-results:
    if: ${{ always() }}
    needs: [flutter-linting, react-linting, backend-linting]
    name:  Lint Check Results
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo Unit Test Results


#======================================================
# Unit Tests
#======================================================

  flutter-unit-tests:
    name: Flutter Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend/flutter_client
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - name: Runs Flutter Unit Tests
        run: flutter test

  react-unit-tests:
    name: REACT Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo REACT: No Unit tests

  backend-unit-tests:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo Backend: No Unit tests

  unit-test-results:
    if: ${{ always() }}
    needs: [flutter-unit-tests, react-unit-tests, backend-unit-tests]
    name: Unit Test Results
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo Unit Test Results


#======================================================
# Integration Tests
#======================================================

  flutter-integration-tests:
    name: Flutter Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend/flutter_client
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - name: Print
        run: |
          echo Flutter: No integration tests
    
  react-integration-tests:
    name: REACT Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo REACT: No integration tests

  backend-integration-tests:
    name: Backend Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo Backend: No integration tests
  
  integration-test-results:
    if: ${{ always() }}
    needs: [flutter-integration-tests, react-integration-tests, backend-integration-tests]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo Integration Test Results


#======================================================
# Results
#======================================================

  dev-results:
    if: ${{ always() }}
    needs: [integration-test-results, unit-test-results, lint-test-results]
    name: Results
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print results
        run: |
          echo "dev-env-ci-results" >> $GITHUB_STEP_SUMMARY
          echo "::debug:: worflow_run.conclusion ${{ github.event.workflow_run.conclusion }}"
          echo "::debug:: worflow_run.referenced_workflows ${{ github.event.workflow_run.referenced_workflows }}"
          echo "::debug:: worflow_run.run_attempt ${{ github.event.workflow_run.run_attempt }}"
          echo "::debug:: worflow_run.triggering_actor ${{ github.event.workflow_run.triggering_actor }}"