name: Flutter_CI

on:
  push:
    branches: ["main"]
    paths: ['frontend/flutter_client/**']
  pull_request:
    branches: ["main"]
    paths: ['frontend/flutter_client/**']

jobs:
  flutter_test:
    name: Run Flutter tests and analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/flutter_client
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
