name: Staging

on:
  workflow_run:
    workflows: [Development]
    types: [completed]
    branches: [main]

jobs:

#======================================================
# Security Testing
#======================================================

  flutter-security-tests:
    name: Flutter Security Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend/flutter_client
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo Flutter: No security tests


#======================================================
# Load Testing
#======================================================

  flutter-load-testing:
    name: Flutter Load Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend/flutter_client
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo Flutter: No load tests


#======================================================
# Regression Testing
#======================================================

  flutter-regression-tests:
    name: Flutter Regression Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend/flutter_client
    timeout-minutes: 5
    # Skipping #
    if: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Print
        run: |
          echo Flutter: No regression tests