name: Unit Tests

on:
  workflow_call:

jobs:
  flutter_unit:
    name: Flutter Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend/flutter_client
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      # - run: flutter analyze
      - run: flutter test